services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: topobre-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: topobre-api
    ports:
      - "3003:3003"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production
    depends_on:
      - postgres
      - redis

  worker:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
    container_name: topobre-worker
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=redis
      - NODE_ENV=production
    depends_on:
      - redis
      - postgres
