services:
  api:
    image: ghcr.io/psousaj/topobre-api:${IMAGE_TAG}
    container_name: topobre-api
    env_file:
      - .env.runtime
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - OTEL_SERVICE_NAME=api
    networks:
      - topobre-net

  worker:
    image: ghcr.io/psousaj/topobre-worker:${IMAGE_TAG}
    container_name: topobre-worker
    env_file:
      - .env.runtime
    environment:
      - OTEL_SERVICE_NAME=worker
    networks:
      - topobre-net

  web:
    image: ghcr.io/psousaj/topobre-web:${IMAGE_TAG}
    container_name: topobre-web
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    env_file:
      - .env.runtime
    environment:
      - OTEL_SERVICE_NAME=worker
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    networks:
      - topobre-net

networks:
  topobre-net:
    driver: bridge
