services:
  web:
    build: ./web
    container_name: topobre-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  api:
    build: ./server
    container_name: topobre-api
    ports:
      - "3003:3003"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production
