version: '3.8'

services:
  web:
    build:
      context: ./web
      target: WebBuilder
      args:
        CLERK_PUBLISHABLE_KEY: ${CLERK_PUBLISHABLE_KEY}
    container_name: topobre-web
    ports:
      - "3000:3000"
    environment:
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
      - NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
      - NODE_ENV=production

  api:
    # image: psousaj/topobre-api:latest
    # container_name: topobre-api
    build:
      context: ./api
      target: ApiBuilder
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
      - NODE_ENV=production
