include:
  - server/postgres.yml
  - server/redis.yml
  - server/grafana.yml
  - server/loki.yml
  - server/prometheus.yml
  - server/tempo.yml
  - server/otel-collector.yml

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: topobre-api
    ports:
      - "3003:3003"
    environment:
      - DATABASE_URL=postgresql://${PGUSER}:${PGPASSWORD}@postgres:5432/${PGDATABASE}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - NODE_ENV=production
      - OTEL_SERVICE_NAME=api
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    depends_on:
      - postgres
      - redis
    networks:
      - topobre-net

  worker:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
    container_name: topobre-worker
    environment:
      - DATABASE_URL=postgresql://${PGUSER}:${PGPASSWORD}@postgres:5432/${PGDATABASE}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - NODE_ENV=production
      - OTEL_SERVICE_NAME=worker
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    depends_on:
      - postgres
      - redis
    networks:
      - topobre-net

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: topobre-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    networks:
      - topobre-net

networks:
  topobre-net:
    driver: bridge

volumes:
  postgres_data: