include:
  - server/postgres.yml
  - server/redis.yml
  - server/grafana.yml
  - server/loki.yml
  - server/prometheus.yml
  - server/tempo.yml
  - server/otel-collector.yml

networks:
  topobre-net:
    driver: bridge

volumes:
  postgres_data:
