version: '3.8'

services:
  web:
    image: psousaj/topobre-web:latest
    container_name: topobre-web
    # build:
    #   context: ./web
    #   dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - NEXT_CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
      - NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
      - NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
      - NODE_ENV=production
    secrets:
      - CLERK_SECRET_KEY
      - CLERK_PUBLISHABLE_KEY

  api:
    image: psousaj/topobre-api:latest
    container_name: topobre-api
    # build:
    #   context: ./api
    #   dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
      - NODE_ENV=production
    secrets:
      - DATABASE_URL
      - CLERK_SECRET_KEY
      - CLERK_PUBLISHABLE_KEY

secrets:
  DATABASE_URL:
    external: true
  CLERK_SECRET_KEY:
    external: true
  CLERK_PUBLISHABLE_KEY:
    external: true
