packages:
  - apps/*
  - packages/*
  - config/*

hoistPattern:
  - '*'

ignoredBuiltDependencies:
  - '@clerk/shared'

onlyBuiltDependencies:
  - bcrypt
  - esbuild
  - msgpackr-extract
  - protobufjs
  - sharp
  - unrs-resolver
