services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    user: "${UID}:${GID}"
    ports:
      - "5432:5432"
    env_file:
      - .env.runtime
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    volumes:
      - ${APPDATA}/postgres:/var/lib/postgresql/data
