services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "${REDIS_PORT:-6379}:6379"  
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    volumes:
      - "${APPDATA:-./appdata}/redis:/data" 
    networks:
      - topobre-net
