services:
  grafana:
    image: grafana/grafana:9.5.3
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana/dashboard-provider.yml:/etc/grafana/provisioning/dashboards/dashboard-provider.yml
      - ./grafana/dashboards.json:/etc/grafana/provisioning/dashboards/dashboards.json
      - ${APPDATA}/grafana:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
      - tempo
    networks:
      - topobre-net