services:
  jaeger:
    image: jaegertracing/all-in-one:1.36
    container_name: jaeger
    ports:
      - "16686:16686"  # UI
      - "14250:14250"  # gRPC
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - topobre-net

networks:
  topobre-net:
    external: true