services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: ${PGHOST}
      KC_DB_PORT: ${PGPORT}
      KC_DB_URL_DATABASE: ${KEYCLOAK_DB}
      KC_DB_USERNAME: ${PGUSER}
      KC_DB_PASSWORD: ${PGPASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "9090:8080"
    depends_on:
      - db
    networks:
      - topobre-net
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 400M
        reservations:
          cpus: '0.1'
          memory: 200M