services:
  app:
    image: jc21/nginx-proxy-manager:latest
    container_name: ng-manager
    restart: unless-stopped
    env_file:
      - .env.runtime
    user: "${UID}:${GID}"
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    environment:
      DB_POSTGRES_HOST: ${PGHOST}
      DB_POSTGRES_PORT: ${PGPORT}
      DB_POSTGRES_USER: ${PGUSER}
      DB_POSTGRES_PASSWORD: ${PGPASSWORD}
      DB_POSTGRES_NAME: ${NG_DB}
    volumes:
      - ${APPDATA}/ng-manager/data:/data
      - ${APPDATA}/ng-manager/letsencrypt:/etc/letsencrypt
    networks:
      - topobre-net