services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: unless-stopped
    privileged: true
    user: "${UID}:${GID}"
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - ${APPDATA}/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - topobre-net
