services:
  cache:
    image: redis:7.4-alpine
    container_name: redis
    restart: always
    ports:
      - "9736:6379"
    command: sh -c "redis-server --save 20 1 --loglevel warning --requirepass \"$${REDIS_PASSWORD}\""
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - cache:/data
    networks:
      - topobre-net

volumes:
  cache:
    driver: local