services:
  tempo:
    image: grafana/tempo:2.4.1
    container_name: tempo
    command: ["-config.file=/etc/tempo/tempo.yaml"]
    user: "1000:1000"
    ports:
      - "3200:3200"
      - "14268:14268"
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo/tempo.yaml
    networks:
      - topobre-net
