name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker images
        run: |
          docker buildx build --build-arg CLERK_PUBLISHABLE_KEY=${{ secrets.CLERK_PUBLISHABLE_KEY }} --build-arg API_URL=${{secrets.API_URL}} --output type=image,name=psousaj/topobre-web:latest,push=true,compression=gzip ./web
          docker buildx build --build-arg CLERK_PUBLISHABLE_KEY=${{ secrets.CLERK_PUBLISHABLE_KEY }} --output type=image,name=psousaj/topobre-api:latest,push=true,compression=gzip ./api

      - name: Upload docker-compose.yml
        uses: actions/upload-artifact@v4
        with:
          name: docker-compose
          path: docker-compose.yml

  deploy:
    runs-on: self-hosted

    needs: build

    steps:
      - name: Download docker-compose.yml
        uses: actions/download-artifact@v4
        with:
          name: docker-compose

      - name: Run Docker Compose
        run: |
          docker compose -f docker-compose.yml up -d
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXT_PUBLIC_API_URL: ${{ secrets.API_URL }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          CLERK_PUBLISHABLE_KEY: ${{ secrets.CLERK_PUBLISHABLE_KEY }}
        

