name: Deploy Infra

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy Infra
        run: docker compose -f docker-compose.infra.yml up -d
