name: Deploy Infra

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Stop infra containers and clean volumes
        run: docker compose -f docker-compose.infra.yml down -v

      - name: Deploy Infra
        run: docker compose -f docker-compose.infra.yml up -d
        env: 
          APPDATA: ${{ vars.APPDATA }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
