name: Deploy Infra

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Tornar o script executável
        run: chmod +x build/scripts/infra.sh

      - name: Rodar script infra.sh
        run: ./build/scripts/infra.sh
        env:
          APPDATA: ${{ vars.APPDATA }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
