name: Deploy Apps

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push API image
        run: |
          docker buildx build \
            --file apps/api/Dockerfile \
            --tag ghcr.io/${{ github.repository_owner }}/topobre-api:latest \
            --push \
            .

      - name: Build and push Web image
        run: |
          docker buildx build \
            --file apps/web/Dockerfile \
            --tag ghcr.io/${{ github.repository_owner }}/topobre-web:latest \
            --push \
            .

      - name: Build and push Worker image
        run: |
          docker buildx build \
            --file apps/worker/Dockerfile \
            --tag ghcr.io/${{ github.repository_owner }}/topobre-worker:latest \
            --push \
            .

  deploy:
    runs-on: self-hosted
    needs: build
    env:
      NEXT_PUBLIC_API_URL: ${{ vars.NEXT_PUBLIC_API_URL }}
      NODE_ENV: ${{ vars.NODE_ENV }}
      PGUSER: ${{ secrets.PGUSER }}
      PGPASSWORD: ${{ secrets.PGPASSWORD }}
      PGDATABASE: ${{ secrets.PGDATABASE }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pull latest images
        run: docker compose -f docker-compose.apps.yml pull

      - name: Stop containers and clean volumes
        run: docker compose -f docker-compose.apps.yml down -v

      - name: Start containers fresh
        run: docker compose -f docker-compose.apps.yml up -d
